"""68 Certain Teas -- precomputed gate patterns for all 68 thekas, ready for OAM Uncertainty.

This is plain data -- no imports, no computation -- so it's meant to live
on the device itself alongside code.py. Everything below is self-contained
since gate_mapping.py and tala_patterns.py (which generated this file)
don't ship to the microcontroller.

TERMS
    tal      A rhythmic cycle: a fixed number of beats (`beats`) with a
             fixed accent pattern.
    theka    A specific sequence of drum strokes that realizes a tal.
             REALIZED has one entry per theka (68 total, across 43 tals).
    bol      The name of a single drum stroke (Dha, Dhin, Na, Tin, ...).
             One bol fires per beat.
    sam      The first, always-accented beat of a tal's cycle.
    tali     A later accented ("clapped") beat.
    khali    A later deliberately UNaccented ("waved") beat.
    plain    An ordinary beat: none of sam, tali, or khali.

CHANNEL LAYOUT
    Each theka's bols and accent types are assigned to Uncertainty's 8
    gate outputs (channels 1-8), fixed regardless of how sparse a theka
    is:
        1..N    bol identity, most-used bol first, one channel each
        8       tali (always, if the tal has any)
        7       sam (only if <= 6 distinct bols leave it free)
        6       khali (only if <= 5 distinct bols leave it free)
        5       plain beats (only if <= 4 distinct bols leave it free)
        4       an alt-voice: the busiest bol round-robins here every
                other hit (only if <= 3 distinct bols leave it free)
    A theka with more than 7 distinct bols has its least-used bols folded
    onto a similar-sounding survivor until 7 remain (see gate_mapping.py
    for that logic) -- channels 1-7 are then all bol identity, with no
    room for sam/khali/plain/alt-voice.

REALIZED
    A list of dicts, one per theka:
        tal, variant, beats   identify the theka
        complexity            distinct-bol count, used by code.py to sort
                               thekas simplest-first
        bol_to_channel        {bol: channel} for that theka's bols
        sam_channel           channel number, or None if unused
        khali_channel         channel number, or None if unused
        plain_channel         channel number, or None if unused
        altvoice_channel      channel number, or None if unused
        altvoice_bol          which bol round-robins onto altvoice_channel,
                               or None
        tali_channel          always 8
        steps                 list[tuple[int, ...]], one tuple per beat:
                               the channel numbers that fire together as a
                               single fixed-width trigger (see code.py)

Source data: DigiTabla.com (digitabla.com/reference/tals-and-thekas).
Built by: Claude (Sonnet) & cubbs, 2026.
"""

REALIZED = [
    {
        'tal': 'Dadra',
        'variant': 'Dadra Theka',
        'beats': 6,
        'complexity': 4,
        'bol_to_channel': {'dha': 1, 'na': 2, 'dhi': 3, 'ti': 4},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (3, 5), (2, 5), (1, 6), (4, 5), (2, 5)],
    },
    {
        'tal': 'Dadra',
        'variant': 'Benares Dadra Theka',
        'beats': 6,
        'complexity': 4,
        'bol_to_channel': {'dhi': 1, 'na': 2, 'dha': 3, 'tu': 4},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (1, 5), (2, 5), (3, 6), (4, 5), (2, 5)],
    },
    {
        'tal': 'Rupak',
        'variant': 'Rupak Theka',
        'beats': 7,
        'complexity': 3,
        'bol_to_channel': {'na': 1, 'ti': 2, 'dhi': 3},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': 4,
        'altvoice_bol': 'na',
        'tali_channel': 8,
        'steps': [(2, 6), (2, 5), (1, 5), (3, 8), (4, 5), (3, 8), (1, 5)],
    },
    {
        'tal': 'Rupak',
        'variant': 'Rupak 2',
        'beats': 7,
        'complexity': 3,
        'bol_to_channel': {'na': 1, 'ti': 2, 'dhi': 3},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': 4,
        'altvoice_bol': 'na',
        'tali_channel': 8,
        'steps': [(2, 7), (2, 5), (1, 5), (3, 8), (4, 5), (3, 8), (1, 5)],
    },
    {
        'tal': 'Rupak',
        'variant': 'Benares Rupak Theka',
        'beats': 7,
        'complexity': 5,
        'bol_to_channel': {'dhin': 1, 'dha': 2, 'tin': 3, 'na': 4, 'tirakita': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3, 6), (4,), (5,), (1, 8), (1,), (2, 8), (2,)],
    },
    {
        'tal': 'Pashto',
        'variant': 'Pashto Theka',
        'beats': 7,
        'complexity': 5,
        'bol_to_channel': {'tin': 1, 'traka': 2, 'dhin': 3, 'dha': 4, 'ge': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (), (2,), (3, 8), (), (4, 8), (5,)],
    },
    {
        'tal': 'Kaharawa',
        'variant': 'Kaharawa Theka',
        'beats': 8,
        'complexity': 6,
        'bol_to_channel': {'na': 1, 'dha': 2, 'ge': 3, 'ti': 4, 'ke': 5, 'dhi': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2, 7), (3,), (1,), (4,), (1,), (5,), (6,), (1,)],
    },
    {
        'tal': 'Dhumali',
        'variant': 'Dhumali Theka',
        'beats': 8,
        'complexity': 5,
        'bol_to_channel': {'dhin': 1, 'traka': 2, 'dha': 3, 'tin': 4, 'dhage': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (1,), (3,), (4,), (2, 6), (1,), (5,), (2,)],
    },
    {
        'tal': 'Dhumali',
        'variant': 'Dhumali 2',
        'beats': 8,
        'complexity': 5,
        'bol_to_channel': {'dhin': 1, 'traka': 2, 'dha': 3, 'tin': 4, 'dhage': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (1,), (3, 8), (4,), (2, 6), (1,), (5, 8), (2,)],
    },
    {
        'tal': 'Basant',
        'variant': 'Basant Theka',
        'beats': 9,
        'complexity': 8,
        'bol_to_channel': {'dha': 3, 'din': 4, 'ta': 1, 'dhet': 5, 'tete': 6, 'kata': 7, 'gadi': 2, 'gana': 2},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (4, 8), (1, 8), (5, 8), (1,), (6, 8), (7,), (2, 8), (2,)],
    },
    {
        'tal': 'Jhap Sawari',
        'variant': 'Jhap Sawari Theka',
        'beats': 9,
        'complexity': 6,
        'bol_to_channel': {'dhi': 1, 'na': 2, 'katta': 3, 'dhidhi': 4, 'nadhi': 5, 'dhina': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (2,), (1, 8), (1,), (2,), (3,), (4,), (5, 8), (6,)],
    },
    {
        'tal': 'Jhaptal',
        'variant': 'Jhaptal Theka',
        'beats': 10,
        'complexity': 3,
        'bol_to_channel': {'dhi': 1, 'na': 2, 'ti': 3},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': 4,
        'altvoice_bol': 'dhi',
        'tali_channel': 8,
        'steps': [(1, 7), (2, 5), (4, 8), (1, 5), (2, 5), (3, 6), (2, 5), (4, 8), (1, 5), (2, 5)],
    },
    {
        'tal': 'Sultal',
        'variant': 'Sultal Theka 1',
        'beats': 10,
        'complexity': 8,
        'bol_to_channel': {'dha': 1, 'din': 3, 'ta': 4, 'kita': 5, 'tete': 6, 'kata': 7, 'gadi': 2, 'gana': 2},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1,), (1,), (3,), (4,), (5, 8), (1,), (6, 8), (7,), (2,), (2,)],
    },
    {
        'tal': 'Sultal',
        'variant': 'Sultal Theka 2',
        'beats': 10,
        'complexity': 7,
        'bol_to_channel': {'din': 1, 'dha': 2, 'ta': 3, 'tete': 4, 'kata': 5, 'gadi': 6, 'gana': 7},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2,), (), (1,), (1,), (3, 8), (), (4, 8), (5,), (6,), (7,)],
    },
    {
        'tal': 'Sultal',
        'variant': 'Sultal Theka 3',
        'beats': 10,
        'complexity': 5,
        'bol_to_channel': {'ghera': 1, 'naga': 2, 'di': 3, 'dha': 4, 'gad': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(4, 7), (1,), (2, 6), (3,), (1, 8), (2,), (5, 8), (3,), (1, 6), (2,)],
    },
    {
        'tal': 'Rudra',
        'variant': 'Rudra Theka',
        'beats': 11,
        'complexity': 8,
        'bol_to_channel': {'dha': 2, 'tet': 4, 'tirakita': 3, 'dhi': 5, 'na': 1, 'tu': 6, 'kat': 7, 'ta': 1},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2,), (4,), (2, 8), (3, 8), (5, 8), (1,), (3, 8), (6, 8), (1, 8), (7, 8), (1,)],
    },
    {
        'tal': 'Rudra',
        'variant': 'Benares Rudra Theka',
        'beats': 11,
        'complexity': 9,
        'bol_to_channel': {'dhi--kra': 4, 'dhinta': 1, 'kat': 2, 'gheranaga': 5, 'takitadha': 6, '-radha-': 3, 'kataghina': 7, '-dha-ra': 3, 'dha': 1},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(4,), (1,), (1, 8), (2, 8), (5, 8), (6,), (3, 8), (7, 8), (3, 8), (1, 8), (2,)],
    },
    {
        'tal': 'Kumbha',
        'variant': 'Kumbha Theka 1',
        'beats': 11,
        'complexity': 9,
        'bol_to_channel': {'dha': 1, 'dhina': 5, 'taka': 6, 'tete': 2, 'ghera': 7, 'naga': 3, 'kata': 3, 'gadi': 4, 'gana': 4},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1,), (5,), (6, 8), (2, 8), (1, 8), (7,), (3, 8), (2, 8), (3, 8), (4, 8), (4,)],
    },
    {
        'tal': 'Kumbha',
        'variant': 'Kumbha Theka 2',
        'beats': 11,
        'complexity': 7,
        'bol_to_channel': {'dha': 1, 'dhin': 2, 'tete': 3, 'kata': 4, 'naka': 5, 'gadi': 6, 'gana': 7},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1,), (2,), (3, 8), (4, 8), (1, 8), (2,), (5, 8), (3, 8), (4, 8), (6, 8), (7,)],
    },
    {
        'tal': 'Kumbha',
        'variant': 'Benares Kumbha Theka',
        'beats': 11,
        'complexity': 7,
        'bol_to_channel': {'dha': 1, 'dina': 2, 'taka': 3, 'tete': 4, 'kata': 5, 'gadi': 6, 'gana': 7},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1,), (2,), (3, 8), (4, 8), (1, 8), (2,), (3, 8), (4, 8), (5, 8), (6, 8), (7,)],
    },
    {
        'tal': 'Ashtamangal 1',
        'variant': 'Ashtamangal 1 Theka',
        'beats': 11,
        'complexity': 5,
        'bol_to_channel': {'dhi': 1, 'na': 2, 'dhage': 3, 'nadha': 4, 'traka': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (2, 6), (1, 8), (1, 8), (2, 6), (1, 8), (1, 8), (2, 6), (3, 8), (4, 8), (5, 8)],
    },
    {
        'tal': 'Ektal',
        'variant': 'Ektal Theka',
        'beats': 12,
        'complexity': 7,
        'bol_to_channel': {'dhin': 1, 'dhage': 2, 'tirakita': 3, 'na': 4, 'tu': 5, 'kat': 6, 'ta': 7},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1,), (1,), (2,), (3,), (5, 8), (4,), (6,), (7,), (2, 8), (3,), (1, 8), (4,)],
    },
    {
        'tal': 'Chautal',
        'variant': 'Chautal Theka',
        'beats': 12,
        'complexity': 8,
        'bol_to_channel': {'dha': 1, 'din': 2, 'ta': 3, 'kita': 5, 'tete': 6, 'kata': 7, 'gadi': 4, 'gana': 4},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1,), (1,), (2,), (3,), (5, 8), (1,), (2,), (3,), (6, 8), (7,), (4, 8), (4,)],
    },
    {
        'tal': 'Khemta',
        'variant': 'Khemta Theka',
        'beats': 12,
        'complexity': 6,
        'bol_to_channel': {'na': 1, 'dhi': 2, 'te': 3, 'dha': 4, 'ti': 5, 'ta': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(4, 7), (3,), (2,), (1, 8), (5,), (1,), (6,), (3,), (2,), (1, 8), (2,), (1,)],
    },
    {
        'tal': 'Lilawati',
        'variant': 'Lilawati Theka',
        'beats': 13,
        'complexity': 5,
        'bol_to_channel': {'dhin': 1, 'traka': 2, 'tin': 3, 'dha': 4, 'ta': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (1,), (4,), (2,), (1, 8), (), (3,), (3,), (5, 8), (2,), (1,), (1, 8), ()],
    },
    {
        'tal': 'Arachartal',
        'variant': 'Arachartal Theka',
        'beats': 14,
        'complexity': 7,
        'bol_to_channel': {'dhi': 1, 'na': 2, 'tirakita': 3, 'dhin': 4, 'tu': 5, 'kat': 6, 'ta': 7},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(4,), (3,), (1, 8), (2,), (5,), (2,), (6, 8), (7,), (3,), (1,), (2, 8), (1,), (1,), (2,)],
    },
    {
        'tal': 'Arachartal',
        'variant': 'Benares Arachartal Theka',
        'beats': 14,
        'complexity': 7,
        'bol_to_channel': {'dhi': 1, 'na': 2, 'dhin': 3, 'tirakita': 4, 'tu': 5, 'kat': 6, 'ta': 7},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (4,), (1, 8), (2,), (5,), (2,), (6, 8), (7,), (1,), (1,), (2, 8), (1,), (1,), (2,)],
    },
    {
        'tal': 'Jhumra',
        'variant': 'Jhumra Theka',
        'beats': 14,
        'complexity': 6,
        'bol_to_channel': {'dhin': 1, 'tirakita': 2, 'dhage': 3, '-dha': 4, 'tin': 5, '-ta': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (4,), (2,), (1, 8), (1,), (3,), (2,), (5,), (6,), (2,), (1, 8), (1,), (3,), (2,)],
    },
    {
        'tal': 'Jhumra',
        'variant': 'Benares Jhumra Theka',
        'beats': 14,
        'complexity': 5,
        'bol_to_channel': {'dhin': 1, 'dha': 2, 'tirakita': 3, 'tin': 4, 'ta': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (2,), (3,), (1, 8), (1,), (2,), (2,), (4, 6), (5,), (3,), (1, 8), (1,), (2,), (2,)],
    },
    {
        'tal': 'Braha 1',
        'variant': 'Braha 1 Theka',
        'beats': 14,
        'complexity': 10,
        'bol_to_channel': {'dha': 6, 'tet': 3, 'dhet': 1, 'dhina': 4, 'naka': 2, 'dhage': 7, 'tete': 3, 'kata': 2, 'gadi': 5, 'gana': 5},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(6,), (3,), (1, 8), (4, 8), (2,), (1, 8), (1, 8), (4, 8), (2,), (7, 8), (3, 8), (2, 8), (5, 8), (5,)],
    },
    {
        'tal': 'Braha 1',
        'variant': 'Benares Braha 1 Theka',
        'beats': 14,
        'complexity': 6,
        'bol_to_channel': {'tirakita': 1, 'dhi': 2, 'na': 3, 'dhage': 4, 'tage': 5, 'tet': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2, 7), (3,), (1, 8), (2, 8), (3,), (4, 8), (1, 8), (4, 8), (1,), (5, 8), (1, 8), (2, 8), (3, 8), (6,)],
    },
    {
        'tal': 'Pharodasta',
        'variant': 'Pharodasta Theka',
        'beats': 14,
        'complexity': 9,
        'bol_to_channel': {'dhin': 3, 'dhage': 6, 'tirakita': 1, 'tu': 7, 'na': 4, 'kat': 2, 'ta': 4, 'dhina': 5, 'kadha': 2},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (3,), (6,), (1,), (7, 8), (4,), (2,), (4,), (5, 8), (2,), (1, 8), (5,), (2, 8), (1,)],
    },
    {
        'tal': 'Dipchandi',
        'variant': 'Dipchandi Theka',
        'beats': 14,
        'complexity': 4,
        'bol_to_channel': {'dha': 1, 'dhin': 2, 'tin': 3, 'ta': 4},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (2, 5), (5,), (1, 8), (1, 5), (3, 5), (5,), (4, 6), (3, 5), (5,), (1, 8), (1, 5), (2, 5), (5,)],
    },
    {
        'tal': 'Dhamar',
        'variant': 'Dhamar Theka 1',
        'beats': 14,
        'complexity': 6,
        'bol_to_channel': {'te': 1, 'dhe': 2, 'ka': 3, 'dha': 4, 'ga': 5, 'ta': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3, 7), (2,), (1,), (2,), (1,), (4, 8), (), (5,), (1,), (1,), (1, 8), (1,), (6,), ()],
    },
    {
        'tal': 'Dhamar',
        'variant': 'Dhamar Theka 2',
        'beats': 14,
        'complexity': 8,
        'bol_to_channel': {'ka': 6, 'dhe': 1, 'te': 2, 'dha': 7, 'ga': 3, 'di': 4, 'na': 5, 'ta': 3},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(6,), (1,), (2,), (1,), (2,), (7, 8), (), (3,), (4,), (5,), (4, 8), (5,), (3,), ()],
    },
    {
        'tal': 'Pancham Sawari',
        'variant': 'Pancham Sawari Theka',
        'beats': 15,
        'complexity': 11,
        'bol_to_channel': {'dhi': 7, 'na': 2, 'dhidhi': 1, 'kat': 3, 'nadhi': 4, 'dhina': 5, 'ti--kra': 6, 'tina': 2, 'tirakita': 6, 'tuna': 2, 'katta': 3},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(7,), (2,), (1,), (3, 8), (1,), (4,), (5,), (6,), (2,), (6,), (2,), (3, 8), (1,), (4,), (5,)],
    },
    {
        'tal': 'Pancham Sawari',
        'variant': 'Benares Pancham Sawari Theka',
        'beats': 15,
        'complexity': 13,
        'bol_to_channel': {'dha': 4, 'dhin': 1, 'dhage': 6, 'nage': 7, 'ti--kra': 2, 'tina': 3, 'katta': 2, 'dhidhi': 5, 'nadhi': 1, 'dhina': 1, 'dha--kra': 2, 'dhindhin': 5, 'dhatit': 4},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(4,), (1,), (6,), (7, 8), (2,), (3,), (3,), (3,), (2,), (5,), (1,), (1, 8), (2,), (5,), (4,)],
    },
    {
        'tal': 'Gajajhampa',
        'variant': 'Gajajhampa Theka',
        'beats': 15,
        'complexity': 9,
        'bol_to_channel': {'dha': 3, 'dhina': 4, 'naka': 1, 'taka': 2, 'tin': 6, 'tete': 7, 'kata': 1, 'gadi': 5, 'gana': 5},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (4,), (1,), (2,), (3, 8), (4,), (1,), (2,), (6,), (1,), (2,), (7, 8), (1,), (5,), (5,)],
    },
    {
        'tal': 'Chhoti Sawari',
        'variant': 'Chhoti Sawari Theka',
        'beats': 15,
        'complexity': 10,
        'bol_to_channel': {'dha': 3, 'di': 1, 'ga': 4, 'na': 5, 'dhu': 6, 'ma': 7, 'ki': 1, 'ta': 2, 'ka': 4, 'dhi': 1},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (), (3,), (1,), (4, 8), (5,), (6,), (7,), (1, 8), (2,), (2,), (4,), (1, 8), (5,), (2,)],
    },
    {
        'tal': 'Tintal',
        'variant': 'Tintal Theka',
        'beats': 16,
        'complexity': 4,
        'bol_to_channel': {'dha': 1, 'dhin': 2, 'tin': 3, 'ta': 4},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (2, 5), (2, 5), (1, 5), (1, 8), (2, 5), (2, 5), (1, 5), (1, 6), (3, 5), (3, 5), (4, 5), (4, 8), (2, 5), (2, 5), (1, 5)],
    },
    {
        'tal': 'Tilwara',
        'variant': 'Tilwara Theka',
        'beats': 16,
        'complexity': 5,
        'bol_to_channel': {'dha': 1, 'dhin': 2, 'tin': 3, 'tirakita': 4, 'ta': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (4,), (2,), (2,), (1, 8), (1,), (3,), (3,), (5, 6), (4,), (3,), (3,), (1, 8), (1,), (2,), (2,)],
    },
    {
        'tal': 'Tilwara',
        'variant': 'Benares Tilwara Theka',
        'beats': 16,
        'complexity': 5,
        'bol_to_channel': {'dhin': 1, 'dha': 2, 'tirakita': 3, 'tin': 4, 'ta': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2, 7), (3,), (1,), (1,), (2, 8), (2,), (4,), (4,), (5, 6), (3,), (1,), (1,), (2, 8), (2,), (1,), (1,)],
    },
    {
        'tal': 'Bari Sawari',
        'variant': 'Bari Sawari Theka',
        'beats': 16,
        'complexity': 10,
        'bol_to_channel': {'dhi': 3, 'na': 4, 'dhidhi': 5, 'dhina': 1, 'ta-traka': 2, 'tuna': 6, 'katta-': 7, 'trakadhina': 1, 'ginadhage': 1, 'nadhatraka': 2},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (4,), (3,), (4,), (5, 8), (1,), (5,), (1,), (2, 8), (6,), (2, 8), (6,), (7, 8), (1,), (1,), (2,)],
    },
    {
        'tal': 'Bari Sawari',
        'variant': 'Bari Sawari 2',
        'beats': 16,
        'complexity': 6,
        'bol_to_channel': {'ta': 1, 'ki': 2, 'dha': 3, 'dhu': 4, 'ma': 5, 'ka': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3, 7), (), (2,), (1,), (4, 8), (5,), (2,), (1,), (1, 8), (2,), (1,), (1,), (6, 8), (), (2, 8), (1,)],
    },
    {
        'tal': 'Jat',
        'variant': 'Jat Theka',
        'beats': 16,
        'complexity': 4,
        'bol_to_channel': {'dha': 1, 'dhin': 2, 'tin': 3, 'ta': 4},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (5,), (2, 5), (5,), (1, 8), (1, 5), (3, 5), (5,), (4, 6), (5,), (3, 5), (5,), (1, 8), (1, 5), (2, 5), (5,)],
    },
    {
        'tal': 'Ikwai',
        'variant': 'Ikwai Theka',
        'beats': 16,
        'complexity': 4,
        'bol_to_channel': {'ghe': 1, 'dha': 2, 'ke': 3, 'ta': 4},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2, 7), (5,), (1, 5), (1, 5), (2, 8), (1, 5), (5,), (1, 5), (4, 6), (5,), (3, 5), (3, 5), (2, 8), (1, 5), (5,), (1, 5)],
    },
    {
        'tal': 'Sitarkhani',
        'variant': 'Sitarkhani Theka',
        'beats': 16,
        'complexity': 5,
        'bol_to_channel': {'dha': 1, '-ka': 2, '-dhi': 3, 'ta': 4, '-ti': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (3,), (2,), (1,), (1, 8), (3,), (2,), (1,), (1, 6), (5,), (2,), (4,), (4, 8), (3,), (2,), (1,)],
    },
    {
        'tal': 'Tappa',
        'variant': 'Tappa Theka 1',
        'beats': 16,
        'complexity': 6,
        'bol_to_channel': {'dhin': 1, 'dha': 2, 'ta': 3, '-ga': 4, '-kra': 5, 'tin': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (), (2,), (4,), (2, 8), (1,), (3,), (5,), (6,), (), (3,), (4,), (2, 8), (1,), (3,), (5,)],
    },
    {
        'tal': 'Tappa',
        'variant': 'Tappa Theka 2',
        'beats': 16,
        'complexity': 6,
        'bol_to_channel': {'dhin': 1, '-ta': 2, 'dha': 3, 'ta': 4, 'ka': 5, 'kat': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3, 7), (1,), (2,), (1,), (3, 8), (1,), (2,), (1,), (4,), (5,), (2,), (6,), (4, 8), (1,), (2,), (1,)],
    },
    {
        'tal': 'Tappa',
        'variant': 'Benares Tappa Theka',
        'beats': 16,
        'complexity': 6,
        'bol_to_channel': {'dha': 1, '-kra': 2, 'dhin': 3, '-ga': 4, 'tin': 5, 'ta': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (2,), (3,), (), (1, 8), (4,), (1,), (5,), (6,), (2,), (5,), (), (1, 8), (4,), (1,), (3,)],
    },
    {
        'tal': 'Panjabi',
        'variant': 'Panjabi Theka',
        'beats': 16,
        'complexity': 5,
        'bol_to_channel': {'dha': 1, 'naka': 2, '-dhin': 3, 'ta': 4, '-tin': 5},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (3,), (2,), (1,), (1, 8), (3,), (2,), (1,), (1, 6), (5,), (2,), (4,), (4, 8), (3,), (2,), (1,)],
    },
    {
        'tal': 'Shikhar',
        'variant': 'Shikhar Theka',
        'beats': 17,
        'complexity': 14,
        'bol_to_channel': {'dha': 1, 'traka': 4, 'dhina': 2, 'naka': 5, 'thun': 2, 'ga': 3, 'dhuma': 1, 'kita': 6, 'taka': 4, 'dhet': 7, 'tete': 7, 'kata': 6, 'gadi': 3, 'gana': 3},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1,), (4,), (2,), (5,), (2, 8), (3,), (2,), (5,), (1, 8), (6,), (4,), (7, 8), (1,), (7, 8), (6,), (3,), (3,)],
    },
    {
        'tal': 'Vishnu',
        'variant': 'Vishnu Theka',
        'beats': 17,
        'complexity': 9,
        'bol_to_channel': {'dha': 3, 'ki': 4, 'ta': 1, 'ka': 2, 'dhu': 5, 'ma': 6, 'dhe': 7, 'dhi': 3, 'na': 2},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (), (4,), (1,), (1, 8), (2,), (5, 8), (6,), (4,), (1,), (1, 8), (2,), (7, 8), (), (3, 8), (2,), (1,)],
    },
    {
        'tal': 'Vishnu',
        'variant': 'Vishnu 2',
        'beats': 17,
        'complexity': 8,
        'bol_to_channel': {'dha': 3, 'ki': 4, 'ta': 1, 'ka': 2, 'dhu': 5, 'ma': 6, 'dhi': 7, 'na': 2},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (), (4, 8), (1,), (1,), (2,), (5, 8), (6,), (4,), (1,), (1, 8), (2,), (3, 8), (), (7, 8), (2,), (1,)],
    },
    {
        'tal': 'Vishnu',
        'variant': 'Vishnu 3',
        'beats': 17,
        'complexity': 4,
        'bol_to_channel': {'dhin': 1, 'na': 2, 'dhi': 3, 'traka': 4},
        'sam_channel': 7,
        'khali_channel': 6,
        'plain_channel': 5,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1, 7), (2, 5), (1, 8), (1, 5), (2, 5), (1, 8), (4, 5), (3, 5), (2, 5), (1, 8), (1, 5), (2, 5), (1, 5), (1, 6), (2, 5), (3, 5), (2, 5)],
    },
    {
        'tal': 'Vishnu',
        'variant': 'Vishnu 4',
        'beats': 17,
        'complexity': 10,
        'bol_to_channel': {'dhin': 7, 'tirakita': 3, 'dhi': 4, 'na': 2, 'tu': 1, 'kat': 1, 'ta': 1, 'dhage': 5, 'nadha': 6, 'traka': 1},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(7,), (3,), (4,), (2,), (1, 8), (2,), (1,), (1,), (3, 8), (4,), (2, 8), (5,), (6, 8), (1,), (5, 8), (6,), (1,)],
    },
    {
        'tal': 'Churamani',
        'variant': 'Churamani Theka',
        'beats': 17,
        'complexity': 8,
        'bol_to_channel': {'dha': 4, 'ka': 5, 'ta': 6, 'tu': 7, 'nna': 2, 'dhi': 1, 'na': 2, 'traka': 3},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(4,), (5,), (6,), (7, 8), (2,), (1, 8), (1,), (2,), (3,), (2, 8), (1,), (1,), (2,), (1, 8), (3,), (1,), (2,)],
    },
    {
        'tal': 'Mayur',
        'variant': 'Mayur Theka',
        'beats': 17,
        'complexity': 10,
        'bol_to_channel': {'dha': 4, 'dhina': 2, 'naka': 1, 'dhe': 5, 'ki': 7, 'ta': 3, 'ka': 1, 'ga': 6, 'di': 2, 'na': 1},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(4,), (4,), (2, 8), (1,), (5,), (5,), (2, 8), (1,), (7,), (3,), (3,), (1,), (6, 8), (2,), (6,), (1,), (3,)],
    },
    {
        'tal': 'Matta',
        'variant': 'Matta Theka 1',
        'beats': 18,
        'complexity': 9,
        'bol_to_channel': {'dha': 4, 'ghi': 5, 'ra': 6, 'na': 1, 'ka': 2, 'te': 7, 'ta': 3, 'ga': 3, 'di': 4},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(4,), (), (5,), (6,), (1, 8), (2,), (5, 8), (6,), (1,), (2,), (7, 8), (7,), (2, 8), (3,), (3, 8), (4,), (3,), (1,)],
    },
    {
        'tal': 'Matta',
        'variant': 'Matta Theka 2',
        'beats': 18,
        'complexity': 7,
        'bol_to_channel': {'na': 1, 'dhi': 2, 'dhin': 3, 'tirakita': 4, 'tu': 5, 'kat': 6, 'ta': 7},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (), (1,), (), (3, 8), (4,), (2, 8), (1,), (5,), (1,), (6, 8), (7,), (4, 8), (2,), (1, 8), (2,), (2,), (1,)],
    },
    {
        'tal': 'Matta',
        'variant': 'Matta Theka 3',
        'beats': 18,
        'complexity': 9,
        'bol_to_channel': {'dha': 6, 'ki': 7, 'ta': 1, 'ka': 3, 'dhin': 2, 'dhi': 2, 'na': 4, 'ga': 5, 'di': 2},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(6,), (), (7,), (1,), (1, 8), (3,), (2, 8), (), (1,), (), (1, 8), (3,), (2, 8), (4,), (5, 8), (2,), (5,), (4,)],
    },
    {
        'tal': 'Lakshmi',
        'variant': 'Lakshmi Theka',
        'beats': 18,
        'complexity': 8,
        'bol_to_channel': {'dhinna': 2, 'dhindha': 3, 'tirakita': 1, 'dhadha': 4, 'tuna': 6, 'kiranaga': 7, 'tage': 5, 'ta-': 5},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2,), (3, 8), (1, 8), (2,), (3, 8), (1, 8), (4, 8), (1,), (4, 8), (1, 8), (2, 8), (3, 8), (1, 8), (6, 8), (7, 8), (5, 8), (5, 8), (1,)],
    },
    {
        'tal': 'Lakshmi',
        'variant': 'Benares Lakshmi Theka',
        'beats': 18,
        'complexity': 6,
        'bol_to_channel': {'dhet': 1, 'dha': 2, 'tirakita': 3, 'dhedhe': 4, '-dha': 5, '-na': 6},
        'sam_channel': 7,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2, 7), (8,), (1, 8), (1,), (2, 8), (8,), (3, 8), (1,), (2, 8), (8,), (1, 8), (2, 8), (3, 8), (1, 8), (4, 8), (5, 8), (6, 8), (1,)],
    },
    {
        'tal': 'Ganesh',
        'variant': 'Ganesh Theka',
        'beats': 18,
        'complexity': 8,
        'bol_to_channel': {'dha': 1, 'dhi': 3, 'ta': 2, 'ki': 5, 'ka': 6, 'di': 7, 'ga': 4, 'na': 4},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(1,), (), (3,), (2,), (3, 8), (2,), (1,), (), (1, 8), (), (5,), (2,), (2, 8), (6,), (1, 8), (7,), (4,), (4,)],
    },
    {
        'tal': 'Shesh',
        'variant': 'Shesh Theka',
        'beats': 19,
        'complexity': 8,
        'bol_to_channel': {'dha': 2, 'ki': 3, 'ta': 1, 'ka': 4, 'dhu': 6, 'ma': 7, 'gadi': 5, 'gana': 5},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2,), (), (3,), (1,), (1, 8), (4,), (6,), (7,), (3, 8), (1,), (1, 8), (4,), (2, 8), (), (1,), (), (2, 8), (5, 8), (5,)],
    },
    {
        'tal': 'Ashtamangal 2',
        'variant': 'Ashtamangal 2 Theka',
        'beats': 22,
        'complexity': 10,
        'bol_to_channel': {'dha': 2, 'ki': 3, 'ta': 1, 'ka': 4, 'dhu': 6, 'ma': 7, 'dhe': 2, 'di': 3, 'ga': 5, 'na': 5},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2,), (), (3,), (1,), (1, 8), (4,), (6, 8), (7,), (3,), (1,), (1, 8), (4,), (2, 8), (), (1,), (), (1, 8), (4,), (2, 8), (3,), (5, 8), (5,)],
    },
    {
        'tal': 'Braha 2',
        'variant': 'Braha 2 Theka',
        'beats': 28,
        'complexity': 9,
        'bol_to_channel': {'dha': 2, 'ta': 1, 'di': 3, 'na': 5, 'ki': 7, 'din': 3, 'te': 6, 'ka': 4, 'ga': 4},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(2,), (), (1,), (), (2, 8), (), (3, 8), (5,), (1,), (), (7, 8), (1,), (2, 8), (), (3, 8), (), (1,), (), (2, 8), (), (6, 8), (6,), (4, 8), (1,), (4, 8), (3,), (4,), (5,)],
    },
    {
        'tal': 'Braha 2',
        'variant': 'Benares Braha 2 Theka',
        'beats': 28,
        'complexity': 8,
        'bol_to_channel': {'dhi': 3, 'na': 4, 'tira': 2, 'kita': 1, 'dha': 6, 'ge': 5, 'tet': 7, 'ta': 1},
        'sam_channel': None,
        'khali_channel': None,
        'plain_channel': None,
        'altvoice_channel': None,
        'altvoice_bol': None,
        'tali_channel': 8,
        'steps': [(3,), (), (4,), (), (2, 8), (1,), (3, 8), (), (4,), (), (6, 8), (5,), (2, 8), (1,), (3, 8), (), (4,), (), (7, 8), (), (6, 8), (5,), (2, 8), (1,), (1, 8), (5,), (2,), (1,)],
    },
]
